config/routes.rb
Appleseed::Application.routes.draw do
  scope '/admin' do
    devise_for :users, :controllers => { :registrations => 'admin/users/registrations' }
  end # scope

  namespace :admin do
    resource :blog do
      resources :posts, :controller => 'blog_posts' do
        collection do
          get  :import
          post :import
          post :preview
        end # collection

        member do
          get   :preview
          patch :publish
        end # member
      end # resources
    end # resource

    resource :settings, :only => %i(show update)
  end # namespace

  # Static page routes for admin namespace.
  get '/admin', :to => 'admin/pages#index', :as => :admin

  resource :blog, :only => %i(show) do
    resources :posts, :controller => 'blog_posts', :only => %i(show)

    resources :tags,  :controller => 'blog_tags',  :only => %i(show)
  end # resource

  # Static page routes.
  get '/about',    :to => 'pages#about',    :as => :about
  get '/about/me', :to => 'pages#about_me', :as => :about_me
  get '/projects', :to => 'pages#projects', :as => :projects

  root 'pages#index'

  mount JasmineRails::Engine => '/jasmine' if defined?(JasmineRails)
end # routes

app/views/admin/pages/index.html.haml
-# app/views/admin/pages/index.html.haml

%h1= I18n.t('admin.index.control_panel')

%h2= I18n.t('admin.blog.breadcrumb')
%p.clearfix
  = I18n.t('admin.index.blog.description')
  %span.right= link_to render_with_icon(I18n.t 'admin.index.blog.link'), admin_blog_path

%h2= I18n.t('admin.settings.breadcrumb')
%p.clearfix
  = I18n.t('admin.index.settings.description')
  %span.right= link_to render_with_icon(I18n.t 'admin.index.settings.link'), admin_settings_path