config/routes.rb
Appleseed::Application.routes.draw do
  scope '/admin' do
    devise_for :users, :controllers => { :registrations => 'admin/users/registrations' }
  end # scope

  namespace :admin do
    resource :blog do
      resources :posts, :controller => 'blog_posts' do
        collection do
          get  :import
          post :import
          post :preview
        end # collection

        member do
          get   :preview
          patch :publish
        end # member
      end # resources
    end # resource

    resource :settings, :only => %i(show update)
  end # namespace

  # Static page routes for admin namespace.
  get '/admin', :to => 'admin/pages#index', :as => :admin

  resource :blog, :only => %i(show) do
    resources :posts, :controller => 'blog_posts', :only => %i(show)

    resources :tags,  :controller => 'blog_tags',  :only => %i(show)
  end # resource

  # Static page routes.
  get '/about',    :to => 'pages#about',    :as => :about
  get '/about/me', :to => 'pages#about_me', :as => :about_me
  get '/projects', :to => 'pages#projects', :as => :projects

  root 'pages#index'

  mount JasmineRails::Engine => '/jasmine' if defined?(JasmineRails)
end # routes

app/views/shared/_breadcrumbs.html.haml
-# app/views/shared/_breadcrumbs.html.haml

- unless @breadcrumbs.blank?
  %nav.breadcrumbs
    - @breadcrumbs.each_with_index do |(name, path), index|
      - if index == @breadcrumbs.length - 1
        = link_to name, '#', :class => 'current'
      - elsif path.blank?
        = link_to name, '#', :class => 'unavailable'
      - else
        = link_to name, path

app/views/shared/_footer.html.haml
%hr
%p.text-center
  A million miles is the difference between a failure and a new chance.
  \--
  %em Martian Proverb

app/views/shared/_header.html.haml
%header.row
  .small-12.columns
    %p.site-title
      = link_to Setting.fetch('title', 'Appleseed CMS'), :root

app/views/shared/_navigation.html.haml
%nav
  %ul.large-block-grid-1{ :class => "small-block-grid-#{current_user ? 5 : 4}"}
    %li= link_to I18n.t('navigation.home'), :root
    %li= link_to I18n.t('navigation.blog'), blog_path
    %li= link_to I18n.t('navigation.projects'), projects_path
    %li= link_to I18n.t('navigation.about'), about_path
    - if current_user
      %li= link_to I18n.t('navigation.admin'), admin_path
  %hr

app/views/shared/_notices.html.haml
-# app/views/shared/_notices.html.haml

- if current_user
  %p
    %span.right
      = link_to destroy_user_session_path, :method => :delete do
        %i.fi-arrow-right
        Sign Out
    %i.fi-torso
    %em You are currently signed in as
    = succeed '.' do
      = current_user.email

- unless flash[:alert].blank?
  .alert-box.warning{ :data => { :alert => true } }
    = render_with_icon flash[:alert]
    = link_to '&times;'.html_safe, '#', :class => 'close'

- unless flash[:notice].blank?
  .alert-box{ :data => { :alert => true } }
    = render_with_icon flash[:notice]
    = link_to '&times;'.html_safe, '#', :class => 'close'