config/routes.rb
Appleseed::Application.routes.draw do
  scope '/admin' do
    devise_for :users, :controllers => { :registrations => 'admin/users/registrations' }
  end # scope

  namespace :admin do
    resource :blog do
      resources :posts, :controller => 'blog_posts' do
        collection do
          get  :import
          post :import
          post :preview
        end # collection

        member do
          get   :preview
          patch :publish
        end # member
      end # resources
    end # resource

    resource :settings, :only => %i(show update)
  end # namespace

  # Static page routes for admin namespace.
  get '/admin', :to => 'admin/pages#index', :as => :admin

  resource :blog, :only => %i(show) do
    resources :posts, :controller => 'blog_posts', :only => %i(show)

    resources :tags,  :controller => 'blog_tags',  :only => %i(show)
  end # resource

  # Static page routes.
  get '/about',    :to => 'pages#about',    :as => :about
  get '/about/me', :to => 'pages#about_me', :as => :about_me
  get '/projects', :to => 'pages#projects', :as => :projects

  root 'pages#index'

  mount JasmineRails::Engine => '/jasmine' if defined?(JasmineRails)
end # routes

app/models/blog_post.rb
# app/models/blog_post.rb

require 'mongoid/sleeping_king_studios/orderable'
require 'mongoid/sleeping_king_studios/sluggable'

class BlogPost
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::SleepingKingStudios::Orderable
  include Mongoid::SleepingKingStudios::Sluggable

  CONTENT_TYPES = %w(plain redcarpet)

  belongs_to :author, :class_name => 'User', :inverse_of => :posts
  belongs_to :blog

  has_many :taggings, :as => :taggable, :dependent => :destroy

  field :title, :type => String

  field :content,      :type => String
  field :content_type, :type => String

  field :published_at, :type => Time

  scope :published, -> {
    where(:published_at.lte => Time.now.utc).desc(:published_order)
  } # end scope

  slugify :title, :lockable => true

  validates :author, :presence => true
  validates :blog, :presence => true
  validates :title, :presence => true
  validates :content_type, :presence => true,
    :inclusion => { :in => CONTENT_TYPES }

  cache_ordering :created_at.desc,  :as => :most_recent_order
  cache_ordering :published_at.asc, :as => :published_order,
    :filter => { :published_at.ne => nil }

  def publish
    self.published_at = Time.now.utc

    if self.save
      true
    else
      self.published_at = nil
      false
    end # if-else
  end # method publish

  def published?
    !self.published_at.blank? && self.published_at <= Time.now.utc
  end # method published?

  ########################
  ### ORDERING HELPERS ###
  ########################

  def first_most_recent
    BlogPost.first_most_recent(BlogPost.where(:blog_id => blog.id))
  end # method first_most_recent

  def last_most_recent
    BlogPost.last_most_recent(BlogPost.where(:blog_id => blog.id))
  end # method last_most_recent

  def next_most_recent
    super BlogPost.where(:blog_id => blog.id)
  end # method next_most_recent

  def prev_most_recent
    super BlogPost.where(:blog_id => blog.id)
  end # method prev_most_recent

  def first_published
    BlogPost.first_published(BlogPost.where(:blog_id => blog.id))
  end # method first_published

  def last_published
    BlogPost.last_published(BlogPost.where(:blog_id => blog.id))
  end # method first_published

  def next_published
    super BlogPost.where(:blog_id => blog.id)
  end # method next_published

  def prev_published
    super BlogPost.where(:blog_id => blog.id)
  end # method prev_published
end # model

app/controllers/admin/blog_posts_controller.rb
# app/controllers/admin/blog_posts_controller.rb

class Admin::BlogPostsController < Admin::AdminController
  before_action :load_dependent_resources
  before_action :build_resource, :only => %i(new create)
  before_action :load_resource, :only => %i(show edit update destroy publish)

  # POST /admin/blog/posts
  def create
    if @blog_post.save && update_taggings
      flash[:notice] = I18n.t('admin.blog_posts.new.success')
      redirect_to admin_blog_post_path(@blog_post)
    else
      breadcrumbs_for :new
      render :new
    end # if-else
  end # action create

  # DELETE /admin/blog/posts/:id
  def destroy
    @blog_post.destroy

    flash[:alert] = I18n.t('admin.blog_posts.delete.success')
    redirect_to admin_blog_path
  end # action destroy

  # GET /admin/blog/posts/:id/edit
  def edit
    breadcrumbs_for :edit
  end # action edit

  # GET /admin/blog/posts/import
  # POST /admin/blog/posts/import
  def import
    if request.get?
      @blog_posts = []
      breadcrumbs_for :import
      render :import and return
    elsif blog_posts_params.nil?
      flash.now[:alert] = I18n.t('admin.blog_posts.import.failure.malformed_json')
      breadcrumbs_for :import
      render :import and return
    end # if-elsif

    build_resources

    if @blog_posts.map(&:valid?).inject(true) { |memo, valid| memo && valid }
      BlogPost.collection.insert(@blog_posts.map &:as_document)
      flash[:notice] = I18n.t('admin.blog_posts.import.success')
      redirect_to admin_blog_path
    else
      flash.now[:alert] = I18n.t('admin.blog_posts.import.failure.invalid_posts')
      breadcrumbs_for :import
      render :import
    end # if-else
  end # action import

  # GET /admin/blog/posts
  def index
    respond_to do |format|
      format.html { redirect_to admin_blog_path }
      format.json do
        load_dependent_resources
        load_resources

        render :index
      end # format
    end # respond_to
  end # action index

  # GET /admin/blog/posts/new
  def new
    breadcrumbs_for :new
  end # action new

  # POST /admin/blog/posts/preview
  # GET  /admin/blog/posts/:id/preview
  def preview
    params[:id] ? load_resource : build_resource

    # Stub taggings.
    @blog_post.taggings = taggings_params.map do |tagging_name|
      Tagging.new :name => tagging_name
    end

    @blog_post_presenter = Admin::BlogPostPresenter.new @blog_post
    breadcrumbs_for :preview
  end # action preview

  # PATCH /admin/blog/posts/:id/publish
  def publish
    if @blog_post.publish
      flash[:notice] = I18n.t('admin.blog_posts.publish.success')
      redirect_to admin_blog_post_path(@blog_post)
    else
      breadcrumbs_for :edit
      render :edit
    end # if-else
  end # action publish

  # GET /admin/blog/posts/:id
  def show
    @blog_post_presenter = Admin::BlogPostPresenter.new @blog_post

    breadcrumbs_for :show
  end # action show

  # PATCH /admin/blog/posts/:id
  def update
    post_params = blog_post_params
    
    if false == post_params[:slug_lock]
      post_params[:slug] = BlogPost.value_to_slug(post_params.fetch('title', @blog_post.title))
    end # if

    if @blog_post.update_attributes(post_params) && update_taggings
      flash[:notice] = I18n.t('admin.blog_posts.edit.success')
      redirect_to admin_blog_post_path(@blog_post)
    else
      breadcrumbs_for :edit
      render :edit
    end
  end # action update

  private

  def blog_post_params
    hsh = params.fetch(:blog_post, {}).permit(:title, :slug, :content, :content_type)
    hsh[:slug_lock] = !hsh[:slug].blank? if hsh.has_key?(:slug)
    hsh
  end # method blog_post_params

  def blog_posts_data
    params.fetch(:blog_posts, {}).fetch(:data, nil)
  end # method blog_posts_data

  def blog_posts_params
    JSON.parse blog_posts_data
  rescue JSON::ParserError
    nil
  end # method blog_posts_params

  def breadcrumbs_for action
    @breadcrumbs << [I18n.t('admin.blog.breadcrumb'), admin_blog_path]
    case action
    when :import
      @breadcrumbs << [I18n.t('admin.blog_posts.breadcrumb')]
      @breadcrumbs << [I18n.t('admin.blog_posts.import.breadcrumb')]
    when :new
      @breadcrumbs << [I18n.t('admin.blog_posts.breadcrumb')]
      @breadcrumbs << [I18n.t('admin.blog_posts.new.breadcrumb')]
    when :preview
      @breadcrumbs << [I18n.t('admin.blog_posts.breadcrumb')]
      @breadcrumbs << [I18n.t('admin.blog_posts.preview.breadcrumb')]
    when :show
      @breadcrumbs << [I18n.t('admin.blog_posts.breadcrumb')]
      @breadcrumbs << [@blog_post.title]
    when :edit
      @breadcrumbs << [I18n.t('admin.blog_posts.breadcrumb')]
      @breadcrumbs << [@blog_post.title, admin_blog_post_path(@blog_post)]
      @breadcrumbs << [I18n.t('admin.blog_posts.edit.breadcrumb')]
    end # case
  end # method breadcrumbs_for

  def build_resource
    post_params = blog_post_params

    if false == post_params[:slug_lock]
      post_params[:slug] = BlogPost.value_to_slug(post_params.fetch('title', ''))
    end # if

    @blog_post = BlogPost.new post_params
    @blog_post.author = current_user
    @blog_post.blog   = @blog
    @blog_post
  end # method build_resource

  def build_resources
    @blog_posts = blog_posts_params.map do |params|
      blog_post = BlogPost.new params.select { |key, _| %w(title content content_type).include?(key) }
      blog_post.author = current_user
      blog_post.blog   = @blog
      blog_post
    end # map
  end # method build_resources

  def load_dependent_resources
    @blog = Blog.first
  end # method load_dependent_resources

  def load_resource
    @blog_post = BlogPost.find params[:id]
  end # method load_resource

  def load_resources
    @blog_posts = @blog ? @blog.posts : []
  end # method load_resources

  def taggings_params
    params.fetch(:blog_post, {}).fetch(:taggings, '').split(', ').map(&:strip).uniq
  end # method taggings_params

  def update_taggings
    names = Set.new(taggings_params)

    # Check for removed taggings.
    @blog_post.taggings.each do |tagging|
      if names.include?(tagging.name)
        # If the tagging exists and is in the set of names, remove the name so
        # that we do not create a duplicate later.
        names.delete tagging.name
      else
        # If the tagging exists and is not in the set of names, destroy the
        # tagging (and remove it from the taggings cached on the model object).
        @blog_post.taggings.delete tagging
        tagging.destroy
      end # if-else
    end # each

    names.each do |name|
      @blog_post.taggings.create :name => name
    end # each

    true
  end # method update_taggings
end # class

app/controllers/blog_posts_controller.rb
# app/controllers/blog_posts_controller.rb

class BlogPostsController < ApplicationController
  before_action :load_dependent_resources
  before_action :load_resource, :only => %i(show)

  # GET /blog/posts/:id
  def show
    breadcrumbs_for :show

    @blog_post_presenter = BlogPostPresenter.new @blog_post
  end # method show

  private

  def breadcrumbs_for action
    @breadcrumbs << [I18n.t('blog.breadcrumb'), blog_path]
    case action
    when :show
      @breadcrumbs << [@blog_post.title]
    end # case
  end # method breadcrumbs_for

  def load_dependent_resources
    @blog = Blog.first
  end # method load_dependent_resources

  def load_resource
    @blog_post = BlogPost.where(:slug => params[:id]).limit(1).first
  end # method load_resource
end # class

app/helpers/admin/blog_posts_helper.rb
# app/helpers/admin/blog_posts_helper.rb

module Admin::BlogPostsHelper
  def select_content_type_tag form, post
    form.select :content_type, options_for_select_content_type
  end # method select_content_type_tag

  private

  def localize_content_type content_type, locale = I18n.locale
    I18n.t("blog_post.content_types.#{content_type}")
  end # method localize_content_type

  def options_for_select_content_type locale = I18n.locale
    BlogPost::CONTENT_TYPES.map do |content_type|
      [localize_content_type(content_type, :locale => locale), content_type]
    end # map
  end # method options_for_select_content_type
end # module

app/views/admin/blog_posts/_form.html.haml
-# app/views/admin/blog_posts/_form.html.haml

- presenter = Admin::BlogPostPresenter.new(post)
= form_for [:admin, post], :builder => FoundationFormBuilder, :html => { :class => 'admin-blog-posts-form', :data => { :"appleseed-layout" => 'Admin.BlogPosts.Form'} } do |form|
  .row
    .large-6.columns
      = form.label :title, t('blog_post.fields.title')
      = form.text_field :title, :autofocus => true
    .large-6.columns
      = form.label :slug, t('blog_posts.fields.slug')
      = form.text_field :slug, :placeholder => post.to_slug, :value => post.slug_lock ? post.slug : ''

  = form.label :taggings, t('models.taggable.tags')
  = text_field_tag :blog_post_taggings, presenter.tagging_names.join(', '), :name => :'blog_post[taggings]'

  = form.label :content_type, t('blog_post.fields.content_type')
  = select_content_type_tag form, post

  = form.label :content, t('blog_post.fields.content')
  = form.text_area :content, :data => { :"appleseed-autosize" => true }

  .text-right
    = link_to t('shared.cancel'), post.persisted? ? admin_blog_post_path(post) :admin_blog_path, :class => 'button secondary radius'
    = link_to render_with_icon(I18n.t 'admin.blog_posts.preview.submit'), '#', :id => 'preview-blog-post-button', :class => 'button radius hide', :data => { :path => preview_admin_blog_posts_path }
    = form.submit render_without_icon(post.persisted? ? t('admin.blog_posts.edit.submit') : t('admin.blog_posts.new.submit')), :class => 'button success radius'

app/views/admin/blog_posts/edit.html.haml
-# app/views/admin/blog_posts/edit.html.haml

= content_for :body_class do
  admin-blog-posts-edit

%h1= I18n.t('admin.blog_posts.edit.title')

= render :partial => 'admin/blog_posts/form', :locals => { :blog => @blog, :post => @blog_post }

app/views/admin/blog_posts/import.html.haml
-# app/views/admin/blog_posts/import.html.haml

= content_for :body_class do
  admin-blog-posts-import

%h1 Import Posts

= form_for :blog_posts, :url => admin_blog_posts_path do |form|
  - @blog_posts.each_with_index do |blog_post, index|
    - unless blog_post.errors.blank?
      .panel.errors
        %strong= I18n.t('admin.blog_posts.import.errors', :index => index + 1, :count => @blog_posts.count)
        %ul
          - blog_post.errors.full_messages.each do |message|
            %li= message

  = text_area_tag :blog_posts_data, params.fetch(:blog_posts, {}).fetch(:data, ''), :name => 'blog_posts[data]', :data => { :"appleseed-autosize" => true }

  .text-right
    = link_to t('shared.cancel'), admin_blog_path, :class => 'button secondary radius'
    = form.submit render_without_icon(I18n.t 'admin.blog_posts.import.submit'), :class => 'button success radius'

app/views/admin/blog_posts/new.html.haml
-# app/views/admin/blog_posts/new.html.haml

= content_for :body_class do
  admin-blog-posts-new

%h1= I18n.t('admin.blog_posts.new.title')

= render :partial => 'admin/blog_posts/form', :locals => { :blog => @blog, :post => @blog_post }

app/views/admin/blog_posts/preview.html.haml
-# app/views/admin/blog_posts/preview.html.haml

%h1= @blog.title

%h2= @blog_post.title

%p{ :style => 'margin-bottom:1rem;' }= I18n.t('blog_post.show.published_by', :author => @blog_post_presenter.author_name, :date => @blog_post_presenter.published_date)

= render :partial => 'blog_posts/show/tags', :locals => { :blog_post => @blog_post, :presenter => @blog_post_presenter }

= render :partial => 'admin/blog_posts/preview/navigation'

= @blog_post_presenter.formatted_content

= render :partial => 'admin/blog_posts/preview/navigation'

app/views/admin/blog_posts/show.html.haml
-# app/views/admin/blog_posts/show.html.haml

= content_for :body_class do
  admin-blog-posts-show

%h1= I18n.t('admin.blog_posts.show.title')

%div{ :data => { :"appleseed-layout" => 'Admin.BlogPosts.Show' } }
  = render :partial => 'admin/shared/modals/confirm_delete', :locals => { :title => I18n.t('admin.blog_posts.delete.confirm.title'), :body => I18n.t('admin.blog_posts.delete.confirm.body', :title => @blog_post.title), :submit => render_with_icon(I18n.t 'admin.blog_posts.delete.submit') }
  %p
    %strong
      = succeed(':') do
        = I18n.t('shared.actions')
    - unless @blog_post.published?
      = link_to render_with_icon(I18n.t 'admin.blog_posts.actions.publish'), publish_admin_blog_post_path(@blog_post), :method => :patch, :class => ' success'
      &mdash;
    = link_to render_with_icon(I18n.t 'admin.blog_posts.actions.preview'), preview_admin_blog_post_path(@blog_post), :target => '_blank'
    &mdash;
    = link_to render_with_icon(I18n.t 'admin.blog_posts.actions.edit'), edit_admin_blog_post_path(@blog_post)
    &mdash;
    = link_to render_with_icon(I18n.t 'admin.blog_posts.actions.export'), admin_blog_post_path(@blog_post, :format => :json), :target => :blank
    &mdash;
    = link_to render_with_icon(I18n.t 'admin.blog_posts.actions.delete'), admin_blog_post_path(@blog_post), :method => :delete, :class => 'alert delete-link'

- nav_options = { :current_post => @blog_post, :first_post => @blog_post.last_most_recent, :prev_post => @blog_post.next_most_recent, :next_post => @blog_post.prev_most_recent, :last_post => @blog_post.first_most_recent }
= render :partial => 'admin/blog_posts/show/navigation', :locals => nav_options

%h2= @blog_post.title

%p
  = succeed(':') do
    %strong= I18n.t('blog_post.fields.slug')
  %i{ :class => @blog_post.slug_lock ? 'fi-lock' : 'fi-unlock' }
  = @blog_post.slug
  %br
  = succeed(':') do
    %strong= I18n.t('models.taggable.tags')
  = @blog_post_presenter.taggings_list
  %br
  = succeed(':') do
    %strong= I18n.t('blog_post.fields.content_type')
  = @blog_post_presenter.localized_content_type
  %br
  = succeed(':') do
    %strong= I18n.t('blog_post.published')
  = @blog_post_presenter.published_mark
  = @blog_post_presenter.published_date

%p
  = succeed(':') do
    %strong= I18n.t('admin.blog_posts.raw_content')
  %br
  = @blog_post_presenter.raw_content

= render :partial => 'admin/blog_posts/show/navigation', :locals => nav_options